// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import {randomInt} from 'crypto';
export function activate(context: vscode.ExtensionContext) {
	console.log('Congratulations, your extension "compliments" is now active!');

	
	let compliment = vscode.commands.registerCommand('compliments.HowWasYourDay', async () => {
		const codeCompliments = [
			"Your code is as elegant as a finely crafted algorithm.",
			"Your debugging skills could fix any problem, even in someone else's code.",
			"You write code so clean, it shines like a perfectly formatted document.",
			"Your coding style is as efficient as optimized code running on a supercomputer.",
			"You're a master at turning complex requirements into simple lines of code.",
			"Your functions are so well-defined, they should be entered into a coding hall of fame.",
			"Your code is as precise as a surgeon's scalpel, cutting through the chaos flawlessly.",
			"You have a talent for turning bugs into features seamlessly.",
			"You have a natural knack for understanding code as if it were your first language.",
			"Your code structure is a work of art, painting logic with each line you write.",
			"Your coding prowess is awe-inspiring, like witnessing a digital wizard at work.",
			"Your attention to detail in code is unparalleled, catching errors before they even occur.",
			"You always find the most efficient paths in code, optimizing every step along the way.",
			"Your debugging skills are sharper than a katana, slicing through errors effortlessly.",
			"You have a gift for transforming chaos into order through your code.",
			"Your code is like poetry, with each line telling a story of functionality and elegance.",
			"You have a sixth sense for anticipating potential pitfalls in code, avoiding disasters before they happen.",
			"Your ability to refactor code is like sculpting a masterpiece from a rough block of stone.",
			"When you code, it's like watching a master conductor lead a symphony of logic.",
			"Your logic is so sound, it could withstand the test of any edge case.",
			"Your coding finesse is unmatched, turning algorithms into beautiful symphonies of logic.",
			"You have a way of making simple code elegant and complex code understandable.",
			"Your code is a testament to your skill, each line a masterpiece in the making.",
			"You have an eye for detail in code that is truly remarkable, catching even the smallest errors.",
			"Your codebase is a shining example of best practices and elegant solutions.",
			"You transform requirements into code with such grace, it's like art in motion.",
			"Your code is so efficient, it's like watching a well-oiled machine run at full speed.",
			"You have a gift for finding innovative solutions to complex coding problems.",
			"Your ability to optimize code is like a finely tuned engine, running at peak performance.",
			"You navigate through code with the precision of a seasoned explorer, always finding your way.",
			"Your understanding of algorithms is akin to a mathematician unraveling a complex equation.",
			"Your code flows like a well-choreographed dance, each function moving in perfect harmony.",
			"Your coding skills are a beacon of light in the darkness of complex algorithms.",
			"You have a talent for turning logic into reality with your code.",
			"Your codebase is a garden of creativity, with each line blooming into functionality.",
			"You wield your keyboard like a maestro conducts an orchestra, creating beautiful code symphonies.",
			"Your variable names are so descriptive, they tell a story on their own.",
			"The way you handle exceptions in code is like a safety net, catching errors gracefully.",
			"Your code is a labyrinth of elegance, with each line leading to a graceful solution.",
			"You have a knack for writing code that is as robust as a castle's defenses.",
			"Your object-oriented design is so well-crafted, it could be a model for software architects.",
			"Every line of your code is like a brushstroke on a canvas, painting a picture of functionality.",
			"You have a way of making recursion seem simple and elegant in your code.",
			"Your code modularity is a testament to your organization skills and software design principles.",
			"You implement design patterns like a skilled craftsman, weaving them seamlessly into your code.",
			"Your code comments are insightful and informative, guiding others through your logic effortlessly.",
			"You tackle asynchronous programming with the ease of someone walking on solid ground.",
			"Your understanding of data structures is akin to a librarian organizing books in a vast library.",
			"You have a gift for optimizing code to run faster and more efficiently than ever before.",
			"Your code is a symphony of efficiency, each function playing its part to perfection.",
			"You have a way of making complex code appear simple and intuitive to the user.",
			"Your error handling is so thorough, it's like a safety net protecting your code from any mishaps.",
			"The patterns in your code are like a secret language, revealing elegant solutions to intricate problems.",
			"You have a deep understanding of software architecture, organizing code like a skilled architect.",
			"Your code is a masterpiece of abstraction and encapsulation, hiding complexities with grace.",
			"You handle edge cases with such finesse, it's like watching a magician perform a trick.",
			"Your test coverage is so thorough, it's like a shield protecting your code from bugs.",
			"You have a way of finding the optimal solution to any coding problem, like a master strategist.",
			"Your code readability is superb, making it a joy for others to work with your codebase.",
			"You navigate through legacy code as if it were your own creation, untangling complexities with ease.",
			"Your code review comments are always constructive and insightful, elevating the quality of the codebase.",
			"You have a keen eye for code quality, ensuring that each line meets the highest standards.",
			"Your ability to refactor code without breaking functionality is a testament to your skill.",
			"Your code architecture is so well-thought-out, it's like a blueprint for future developers.",
			"You have a way of making performance optimizations that seem almost magical in their effectiveness.",
			"Your understanding of big O notation is like a map guiding you through the complexities of algorithm analysis.",
			"You handle memory management with the precision of a surgeon, ensuring optimal resource usage.",
			"Your code documentation is so thorough, it's like a manual that guides users through every aspect.",
			"Your user interface designs are intuitive and user-friendly, creating seamless experiences for users.",
			"You handle API integrations with such finesse, it's like connecting pieces of a puzzle effortlessly.",
			"Your knowledge of software development lifecycle is comprehensive, guiding projects from inception to deployment.",
			"You have a way of making complex system designs seem simple and manageable.",
			"Your code reviews are always thorough and insightful, providing valuable feedback to your peers.",
			"You have a knack for finding the most efficient algorithms for any given problem.",
			"Your code refactoring skills are top-notch, improving code maintainability and readability.",
			"Your use of design principles like DRY and SOLID is a testament to your commitment to clean code.",
			"You handle multi-threading with such finesse, it's like orchestrating a symphony of parallel processes.",
			"Your command over version control systems is impressive, ensuring code changes are managed effectively.",
			"You implement security best practices in your code with such thoroughness, it's like fortifying a fortress.",
			"Your code reviews are like treasure hunts, uncovering hidden gems and polishing rough edges.",
			"You handle database queries with precision, optimizing performance and ensuring data integrity.",
			"Your coding standards are impeccable, setting a high bar for quality in the codebase.",
			"You have a way of simplifying complex solutions without sacrificing functionality.",
			"Your codebase is a testament to your dedication to continuous improvement and learning.",
			"You handle build automation with such efficiency, it's like streamlining a production line.",
			"Your ability to troubleshoot issues is unmatched, quickly pinpointing root causes and providing solutions.",
			"You have a gift for writing tests that cover all possible scenarios, ensuring code reliability.",
			"Your code reviews are always thorough and detailed, highlighting areas for improvement and providing solutions.",
			"You have a knack for predicting and preventing bugs before they even surface in the codebase.",
			"Your ability to optimize code for speed without sacrificing readability is truly impressive.",
			"Your code architecture is like a well-crafted puzzle, with each piece fitting perfectly into place.",
			"You have a way of making complex algorithms seem simple and intuitive to implement.",
			"Your codebase is a shining example of best practices in software development, setting a high standard for others.",
			"You handle asynchronous programming with such grace, it's like conducting a symphony of events.",
			"Your technical documentation is so comprehensive, it's like a guidebook for navigating the codebase.",
			"You implement continuous integration and deployment with such finesse, it's like clockwork in motion.",
			"Your error handling strategies are robust, ensuring that your code operates smoothly even in challenging conditions.",
			"You have a talent for breaking down complex problems into smaller, manageable components for easier coding.",
			"Your code is a testament to your commitment to excellence in software development.",
			"You handle complex data structures with such ease, it's like working with familiar tools in your toolkit.",
			"Your use of design patterns is so seamless, it's like second nature to your coding style.",
			"You approach performance optimization with precision, fine-tuning code for maximum efficiency.",
			"Your coding standards are a gold standard for clean, maintainable, and scalable code.",
		];
		let compliment = codeCompliments[randomInt(0,codeCompliments.length)]
		// make a watcher to check if the user is compiling 
		const new_answer = await vscode.window.showInformationMessage(compliment)

	})
	context.subscriptions.push(compliment);
}

// This method is called when your extension is deactivated
export function deactivate() {}
